= IVO FIS File Consumer

An example project showing how to do file idempotent consumption in Camel.

:toc:

.The idea of the sample
****
The sample is used to show how we can achieve the following objectives 

. Parse Input files and using https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html-single/apache_camel_development_guide/index#MsgEnd-Idempotent[Idempotent consumer]  to filter out files processed.
For the full file component attributes please check https://access.redhat.com/documentation/en-us/red_hat_fuse/7.3/html-single/apache_camel_component_reference/index#file-component[File Component]
+
[width="100%",options="header,footer"]
|====================
| idempotentKey (filter) |  To use a custom idempotent key. By default the absolute path of the file is used. You can use the File Language, for example to use the file name and file size, you can do: idempotentKey=$file:name-$file:size
| idempotentRepository (filter) |  A pluggable repository org.apache.camel.spi.IdempotentRepository which by default use MemoryMessageIdRepository if none is specified and idempotent is true.
|====================

. Ensure that in case of clustering only one application pod is processing file 
+
[width="100%",options="header,footer"]
|====================
| readLock (lock) |  Used by consumer, to only poll the files if it has exclusive read-lock on the file (i.e. the file is not in-progress or being written). Camel will wait until the file lock is granted. idempotent - (only for file component) idempotent is for using a idempotentRepository as the read-lock. This allows to use read locks that supports clustering if the idempotent repository implementation supports that. 
|====================
+
[source,java]
----
...
fromF("file:%s?noop=true&moveFailed=.failed&readLock=idempotent&idempotentRepository=#fileMessageIdRepository&idempotentKey=${file:name}-${file:size}", properties.getFile().getMessagesDirectory()).routeId("fileConsumerRoute")
...
----
. Ensure that no duplicate record is processed, in case the pod failed in the middle of the processing of a file. Again we will use idempotent consumer
+
[source,java]
----
...
from("direct:dbInsert").routeId("dbInserterRoute").tracing().transacted("requiredTransactionPolicy").split().body()
.log("dbInsert ${header.BERBER_ZAAK_GEGEVENS_FILE_LOCATION}, Body = ${body}").idempotentConsumer(simple("${header.BERBER_ZAAK_GEGEVENS_FILE_LOCATION}_${body.id}"),applicationContext.getBean("dbMessageIdRepository", IdempotentRepository.class)).eager(true).log("Inserting into DB...")
...
----
****

== Preparing
We will use MySql DB to hold information about the Files under processing and also records processed (idempotentRepository). Camel is expecting a table named https://github.com/apache/camel/blob/master/components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java[CAMEL_MESSAGEPROCESSED] according to a specified structure. This table is created part of application pipeline initialization check link:src/main/resources/schema-mysql.sql[schema-mysql.sql] 
Also MySql will have a table "BERBER_ZAAK_GEGEVENS" which will hold all the data uploaded from CSV files

===  Create the project
[source,shell]
----
oc new-project amq7-s2i
----

===  Add the pipeline buildconfig
[source,shell]
----
oc create -f build-pipeline.yaml
----

== Upload CSV files
To upload the csv files for processing, get the current running Pods 
[source,shell]
----
oc get po
----
then upload all the CSV files from current folder to the target POD. use the following command.
[source,shell]
----
cd <location_of_csv_files>
oc rsync . <pod_id>:/deployments/messages
----
== Check data in mySql
Last thing is to check the uploaded data
[source,shell]
----
oc rsh <mysql_pod>
mysql -u user -h mysql sampledb -p
----
password of mysql is passw0rd, then you check both tables "BERBER_ZAAK_GEGEVENS", "CAMEL_MESSAGEPROCESSED" for their data


