spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: DB_MYSQL_USERNAME
            valueFrom:
             secretKeyRef:
               name: mysql
               key: database-user
          - name: DB_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: database-password
          - name: DB_MYSQL_DATABASENAME
            valueFrom:
              secretKeyRef:
                name: mysql
                key: database-name                 
          - name: DB_MYSQL_JDBCURL
            value: jdbc:mysql://mysql/$(DB_MYSQL_DATABASENAME)
