apiVersion: v1
kind: Service
metadata:
  name: fis-file-parser
  labels:
    app: fis-file-parser
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: fis-file-parser
  type: ClusterIP