apiVersion: v1
kind: Service
metadata:
  name: ivo-fis-file-parser
  labels:
    app: ivo-fis-file-parser
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ivo-fis-1
  type: ClusterIP